Added AVPlayer rate observing
aol-public/OneMobileSDK-videorenderer-ios pull request #22
Opened 2017-08-30 12:15 UTC by OleksandrPavliuk

@aol-public/mobile-sdk-team: Ready for review.

2017-08-30 13:35 UTC, oleksii-demedetskyi submitted a review, later dismissed
Add a description of what you want to achieve with this PR, why we need it, etc.

2017-08-30 13:45 UTC, OleksandrPavliuk commented
@AlexeyDemedetskiy Description extended.

2017-08-30 13:54 UTC, AndriiMoskvin commented
@OleksandrPavliuk Don't understand why we need `AVPlayer.rate` observing.

2017-08-30 13:54 UTC, AndriiMoskvin requested changes
@OleksandrPavliuk Don't understand why we need AVPlayer.rate observing.

2017-08-31 12:54 UTC, OleksandrPavliuk commented
@AndriiMoskvin as i mentioned [here](https://github.com/vidible/mobile-sdk-ios/pull/569) 
We need it to track play/pause on tvOS

2017-08-31 12:56 UTC, OleksandrPavliuk commented
@AndriiMoskvin @AlexeyDemedetskiy please take a look ones again

2017-08-31 13:01 UTC, AndriiMoskvin requested changes

2017-08-31 13:01 UTC, AndriiMoskvin commented on VideoRenderer/VideoRenderer/SystemPlayerObserver.swift
>              func emitDidChangeRate(for timebase: CMTimebase) {
`emitDidChangeRate` -> `emitDidChangeTimebaseRate `

2017-08-31 13:01 UTC, AndriiMoskvin commented on VideoRenderer/VideoRenderer/SystemPlayerObserver.swift
> +            if let newItem = newValue() as Float? {
`guard` here is preferred.

2017-08-31 13:23 UTC, OleksandrPavliuk commented on VideoRenderer/VideoRenderer/SystemPlayerObserver.swift
> +            if let newItem = newValue() as Float? {
Adjusted.

2017-08-31 13:23 UTC, OleksandrPavliuk commented on VideoRenderer/VideoRenderer/SystemPlayerObserver.swift
>              func emitDidChangeRate(for timebase: CMTimebase) {
Adjusted.

2017-08-31 13:25 UTC, AndriiMoskvin requested changes

2017-08-31 13:25 UTC, AndriiMoskvin commented on VideoRenderer/VideoRenderer/SystemPlayerObserver.swift
> +            self.emit(.didChangeRate(to: newItem))
`self` could be dropped.

2017-08-31 13:32 UTC, OleksandrPavliuk commented on VideoRenderer/VideoRenderer/SystemPlayerObserver.swift
> +            self.emit(.didChangeRate(to: newItem))
Done.

2017-08-31 15:08 UTC, AndriiMoskvin approved these changes

2017-09-01 11:41 UTC, merged